# -*- coding: utf-8 -*-
"""procesador_imagenes.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i-ZNPeXEgiLqkFOUpCFnncNQS2XajhS_
"""

# procesador_imagenes.py
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression


def ejecutar_pipeline_imagenes(ruta_archivo, carpeta_salida='reporte_output'):
    """
    Pipeline automatizado para limpiar, transformar y analizar la productividad
    del Departamento de Imágenes Médicas. Guarda reportes visuales automáticamente.
    """
    if not os.path.exists(carpeta_salida):
        os.makedirs(carpeta_salida)
        print(f"📁 Carpeta '{carpeta_salida}' creada para los resultados.")

    print("⏳ Iniciando procesamiento automático...")

    # 1. Carga y Limpieza
    df_raw = pd.read_excel(ruta_archivo, skiprows=3)
    df_clean = df_raw.dropna(subset=['ESTUDIO']).copy()
    df_clean['ESTUDIO'] = df_clean['ESTUDIO'].str.replace('**', '', regex=False).str.strip()

    exclude = ['SUB-TOTAL', 'TOTAL GENERAL', 'M.NUCLEAR.']
    df_estudios = df_clean[~df_clean['ESTUDIO'].isin(exclude)].copy()

    meses = ['ENERO', 'FEBRERO', 'MARZO', 'ABRIL', 'MAYO', 'JUNIO', 'JULIO', 'AGOSTO', 'SEPTIEMB', 'OCTUBRE', 'NOVIEMB', 'DICIEMB']
    for m in meses:
        df_estudios[m] = pd.to_numeric(df_estudios[m], errors='coerce').fillna(0).astype(int)

    # Transformación a Formato Largo (Melt)
    df_long = pd.melt(df_estudios, id_vars=['ESTUDIO'], value_vars=meses, var_name='MES', value_name='CANTIDAD')

    # 2. Segmentación de Complejidad
    def clasificar_complejidad(estudio):
        if estudio in ['RX', 'SONOGRAFIAS', 'DENSITOMETRIAS', 'MAMOGRAFIAS']:
            return 'Alta Rotación / Baja Complejidad'
        elif estudio in ['TOMOGRAFIAS', 'RESONANCIAS', 'M.NUCLEAR. ESTUDIOS']:
            return 'Alta Complejidad / Mayor Tiempo'
        elif estudio in ['BIOPSIAS', 'RIV/DRENAJE/TOMODIRIGIDAS', 'ANGIOGRAFIAS(RIV)', 'M.N. PROCEDIMIENTOS']:
            return 'Procedimientos Intervencionistas'
        else:
            return 'Otros'

    df_long['COMPLEJIDAD'] = df_long['ESTUDIO'].apply(clasificar_complejidad)
    print("✅ Datos transformados y segmentados.")

    # 3. Generación de Gráficos (Modo silencioso, directo a disco)
    sns.set_theme(style="whitegrid")

    # Gráfico 1: Complejidad
    resumen_c1 = df_long.groupby('COMPLEJIDAD')['CANTIDAD'].sum().reset_index().sort_values(by='CANTIDAD', ascending=False)
    fig1, ax1 = plt.subplots(figsize=(10, 5))
    sns.barplot(data=resumen_c1, x='CANTIDAD', y='COMPLEJIDAD', palette='Blues_r', ax=ax1)
    ax1.set_title('Carga Operativa por Segmento de Complejidad', fontsize=12, fontweight='bold', pad=10)
    for idx, fila in enumerate(resumen_c1.itertuples()):
        pct = (fila.CANTIDAD / resumen_c1['CANTIDAD'].sum()) * 100
        ax1.text(fila.CANTIDAD + 2000, idx, f"{fila.CANTIDAD:,} ({pct:.1f}%)", va='center', fontweight='bold', fontsize=9)
    ax1.set_xlim(0, resumen_c1['CANTIDAD'].max() * 1.15)
    plt.tight_layout()
    fig1.savefig(f'{carpeta_salida}/1_distribucion_complejidad.png', dpi=300)
    plt.close(fig1)

    # Gráfico 2: Modalidades
    top_e = df_long.groupby('ESTUDIO')['CANTIDAD'].sum().reset_index().sort_values(by='CANTIDAD', ascending=False)
    fig2, ax2 = plt.subplots(figsize=(12, 6))
    sns.barplot(data=top_e, x='ESTUDIO', y='CANTIDAD', palette='viridis', ax=ax2)
    ax2.set_xticklabels(ax2.get_xticklabels(), rotation=45, ha='right')
    ax2.set_title('Volumen Anual por Modalidad de Imagenología', fontsize=12, fontweight='bold', pad=10)
    plt.tight_layout()
    fig2.savefig(f'{carpeta_salida}/2_volumen_modalidades.png', dpi=300)
    plt.close(fig2)

    # Gráfico 3: Línea de Tiempo Temporal
    df_temp = df_long[df_long['ESTUDIO'].isin(['SONOGRAFIAS', 'RX', 'TOMOGRAFIAS', 'RESONANCIAS'])].copy()
    fig3, ax3 = plt.subplots(figsize=(14, 6))
    sns.lineplot(data=df_temp, x='MES', y='CANTIDAD', hue='ESTUDIO', marker='o', linewidth=2, ax=ax3)
    ax3.set_xticklabels(meses)
    ax3.set_title('Comportamiento Temporal de Servicios Clave', fontsize=12, fontweight='bold', pad=10)
    plt.tight_layout()
    fig3.savefig(f'{carpeta_salida}/3_tendencia_temporal.png', dpi=300)
    plt.close(fig3)

    # KPIs de salida en consola
    total_general = df_long['CANTIDAD'].sum()
    promedio_mensual = total_general / 12

    print("\n🎉 ¡Pipeline ejecutado con éxito!")
    print(f"📦 Gráficos guardados en: '{carpeta_salida}/'")
    print("-" * 50)
    print(f"📈 Total Estudios Procesados: {total_general:,}")
    print(f"🗓️ Promedio de Producción Mensual: {int(promedio_mensual):,} estudios/mes")
    print("-" * 50)

    return df_long


def entrenar_predictor_estudios(df_historico_largo, modalidad_objetivo):
    """
    Toma la data acumulada de 3 años de una modalidad (ej. 'TOMOGRAFIAS'),
    entrena un modelo lineal con estacionalidad y predice los 12 meses del próximo año.
    """
    # 1. Filtrar la data por la modalidad que queremos predecir
    df_mod = df_historico_largo[df_historico_largo['ESTUDIO'] == modalidad_objetivo].copy()
    
    # Asegurar que la data esté ordenada cronológicamente (esto es vital en series de tiempo)
    # Nota: Asumiendo que construiste una columna 'FECHA' o un índice correlativo (1 al 36)
    # Crearemos un índice de tiempo simple (Mes 1, Mes 2... Mes 36)
    df_mod['TIMESTEP'] = range(1, len(df_mod) + 1)
    
    # 2. Ingeniería de Características (Feature Engineering) para la Estacionalidad
    # Convertimos los meses en columnas binarias (Variables Dummy)
    # Si es Enero -> ENERO=1, los demás meses=0. Así el modelo lineal aprende el "peso" de cada mes.
    dummies_mes = pd.get_dummies(df_mod['MES'], drop_first=False)
    
    # Unimos el paso del tiempo (Tendencia) con los meses (Estacionalidad)
    X = pd.concat([df_mod[['TIMESTEP']], dummies_mes], axis=1)
    y = df_mod['CANTIDAD']
    
    # 3. Entrenar el Modelo Lineal
    modelo = LinearRegression()
    modelo.fit(X, y)
    
    # 4. Construir el escenario futuro (Los próximos 12 meses, ej: meses 37 al 48)
    futuro_timesteps = range(len(df_mod) + 1, len(df_mod) + 13)
    meses_orden = ['ENERO', 'FEBRERO', 'MARZO', 'ABRIL', 'MAYO', 'JUNIO', 'JULIO', 'AGOSTO', 'SEPTIEMB', 'OCTUBRE', 'NOVIEMB', 'DICIEMB']
    
    df_futuro = pd.DataFrame({
        'TIMESTEP': futuro_timesteps,
        'MES': meses_orden
    })
    
    # Aplicar el mismo One-Hot Encoding al futuro para que el modelo lo entienda
    dummies_futuro = pd.get_dummies(df_futuro['MES']).reindex(columns=dummies_mes.columns, fill_value=0)
    X_futuro = pd.concat([df_futuro[['TIMESTEP']], dummies_futuro], axis=1)
    
    # 5. Hacer la predicción
    df_futuro['PREDICCION_CANTIDAD'] = modelo.predict(X_futuro).astype(int)
    
    print(f"🔮 Predicción completada para la modalidad: {modalidad_objetivo}")
    return df_futuro[['MES', 'PREDICCION_CANTIDAD']]